Repository mellychat/webapp, pull requests merged in 2020-10, with the labels that each got.

#13 Fixed a typo in index.html
  index.html
Labels: bug

#16 Adds actions for releasing to firebase hosting for #1
  .firebase/hosting..cache
  .firebase/hosting.RmlyZWJhc2VSVEMvcHVibGlj.cache
  .firebaserc
  .github/workflows/deploy-firebase-hosting-nightly.yml
  .github/workflows/deploy-firebase-hosting-prod.yml
  .gitignore
  docs/firebase.md
Labels: documentation, enhancement

#17 Fixes Firebase Hosting Weekly deploy.
  .github/workflows/deploy-firebase-hosting-prod.yml
Labels: bug

#20 Refactor Firebase RTC pages
  FirebaseRTC/public/priorIndex.html
  public/assets/css/firebase.css
  public/assets/css/patientSignUp.css
  public/components/firebase/app.js
  public/templates/firebase.html
  public/templates/patientSignUp.html
Labels: assignment
