Repository mellychat/webapp, pull requests merged in 2021-01, with the labels that each got.

#48 Clean up code in prSignUp.css
  public/assets/css/prSignUp.css
  public/templates/prSignUp.html
Labels: assignment, clean-up

#47 Commented/cleaned up code in patientSignUp html, css, and js files
  public/assets/css/patientSignUp.css
  public/assets/css/prSignUp.css
  public/components/patientSignUp.js
  public/templates/patientSignUp.html
Labels: bug, clean-up, documentation, no-pr-activity

#58 DX: Adds tools for auto formatting code using the Prettier tool.
  .devcontainer/devcontainer.json
  .github/workflows/format-on-pr.yml
  .vscode/extensions.json
  .vscode/settings.json
  package-lock.json
  package.json
  workspace.code-workspace
Labels: dx, enhancement, no-pr-activity

#59 Prettify the project.
  .devcontainer/devcontainer.json
  .github/workflows/deploy-firebase-hosting-nightly.yml
  .github/workflows/deploy-firebase-hosting-prod.yml
  .github/workflows/deploy-firebase-hosting-pull-request.yml
  .github/workflows/nag-on-stale-pr.yml
  .vscode/extensions.json
  README.md
  docs/firebase.md
  firebase.json
  public/assets/css/finesse_match.css
  public/assets/css/firebase.css
  public/assets/css/patWaitingRoom.css
  public/assets/css/patientSignUp.css
  public/assets/css/prSignUp.css
  public/assets/css/reviewPage.css
  public/components/firebase.js
  public/components/patientSignUp.js
  public/components/prSignUp.js
  public/templates/firebase.html
  public/templates/index.html
  public/templates/patWaitingRoom.html
  public/templates/patientSignUp.html
  public/templates/prSignUp.html
  public/templates/prWaitingRoom.html
  public/templates/reviewPage.html
Labels: clean-up

#44 Added comments to patWaitingRoom.html
  public/assets/css/patWaitingRoom.css
  public/templates/patWaitingRoom.html
  temp/patientSignUp.html
Labels: assignment

#57 DX: Add a random hacker law to an opened PR
  .github/workflows/main.yml
Labels: dx, enhancement, no-pr-activity

#61 Updated classes + ids in prWaitingRoom.html and its linked files
  public/assets/css/prWaitingRoom.css
  public/components/firebase.js
  public/templates/prWaitingRoom.html
Labels: clean-up

#78 Fixes firestore rules
  firebase.json
  firebase.rules.json
  firestore.rules.json
Labels: bug

#79 Creates a mochajs based testing harness
  .devcontainer/devcontainer.json
  .gitignore
  README.md
  database.rules.json
  docs/testing.md
  firebase.json
  package-lock.json
  package.json
  test/firestore.test.js
Labels: enhancement

#83 Upgraded firebase-tools to fix high vulnerabilities
  package-lock.json
  package.json
Labels: bug
