Repository mellychat/webapp, pull requests merged in 2021-02, with the labels that each got.

#84 Adds Firestore Excercise.
  package-lock.json
  package.json
  test/ex01/README.md
  test/ex01/constants.js
  test/ex01/solution.js
  test/ex01/template.js
  test/ex01/unit.test.js
Labels: assignment

#97 Fixed The Video Positioning
  public/assets/css/demo.css
Labels: bug

#98 Refactored NavBar to All Relevant Pages
  public/components/navBar.js
  public/templates/demo.html
  public/templates/firebase.html
  public/templates/index.html
  public/templates/navBar.html
  public/templates/patWaitingRoom.html
  public/templates/patientSignUp.html
  public/templates/prSignUp.html
  public/templates/prWaitingRoom.html
  public/templates/reviewPage.html
Labels: enhancement

#103 Remove unnecessary imports in nav bar html.
  public/templates/navBar.html
Labels: clean-up

#71 Create developersetup.md
  docs/developersetup.md
Labels: documentation

#88 Update README.md
  README.md
Labels: documentation

#102 Removes unused imgfix dependency.
  public/assets/js/custom.js
  public/assets/js/imgfix.min.js
  public/templates/firebase.html
  public/templates/index.html
  public/templates/patWaitingRoom.html
  public/templates/patientSignUp.html
  public/templates/prSignUp.html
  public/templates/prWaitingRoom.html
  public/templates/reviewPage.html
Labels: clean-up

#85 Removed glitch media files
  public/assets/images/about-icon-01.jpg
  public/assets/images/about-icon-01.png
  public/assets/images/about-icon-02.jpg
  public/assets/images/about-icon-02.png
  public/assets/images/about-icon-03.jpg
  public/assets/images/about-icon-03.png
  public/assets/images/banner-bg.png
  public/assets/images/favicon.jpg
  public/assets/images/laptop-image.jpg
  public/assets/images/left-image.png
  public/assets/images/phone-wire.jpg
  public/assets/images/right-image.png
  public/assets/images/slider-icon.png
  public/assets/images/virtual-conversation.jpg
  public/templates/demo.html
  public/templates/firebase.html
  public/templates/index.html
  public/templates/patWaitingRoom.html
  public/templates/patientSignUp.html
  public/templates/prSignUp.html
  public/templates/prWaitingRoom.html
  public/templates/reviewPage.html
Labels: clean-up
